name: Lint

on: [pull_request]

jobs: 
  lint-extension: 
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # to comment on PR
    steps: 
    - uses: actions/checkout@v3
    - name: Run extension linter   
      uses: mathiasvr/command-output@v2.0.0
      id: lint
      with:
        run: npx web-ext lint
    
    - name: Find previous lint comment 
      uses: peter-evans/find-comment@v2
      if: ${{ always() }}
      id: lint-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: <!-- [bot] lint-results -->

    - name: PR comment with lint results 
      uses: peter-evans/create-or-update-comment@v3
      if: ${{ always() }}
      with:
        comment-id: ${{ steps.lint-comment.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        edit-mode: replace
        body: |
          <!-- [bot] lint-results -->
          ### Lint results
          ${{ steps.lint.outputs.stdout }}
        